/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "bspatch.h"

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_me_ele_patch_BsPatch_patch
  (JNIEnv *, jobject, jstring argv1, jstring argv2, jstring argv3);

#ifdef __cplusplus
}
#endif
